name: Run tests
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3 # clone
      - run: bundle install
      - run: bundle exec fastlane tests